### ISSUE TITLE
Fine tuning design

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#292]

**Comment by NPadrutt** [comment]
Color is in some parts to dark (transactionslist). Maybe take another color (cyan?) or a lighter variant of the existing.

**Comment by ueman** [comment]
Yeah, I noticed it too. I've changed the AppAccentColor to PhoneAccentColor (that is the reason the BottomAppBar is Cyan in my screenshot) and I really like the idea of a more light color.

**Comment by NPadrutt** [comment]
The thing is, I don't like all accent colors in the design. Because of that I tend to set one fix. cyan looks pretty nice so far.

**Comment by NPadrutt** [comment]
I set another color. I pretty like it so far.

**Comment by ueman** [comment]
yep, it looks really good. Do you have any plans to change the black list items in the account page? In my opinion it looks a bit bad and bland.

**Comment by NPadrutt** [comment]
mh, not sure yet. I like it so far. But maybe just because it's "new and shiny".. or so ^^ 
what would you suggest instead?

**Comment by ueman** [comment]
See my pull request
