### ISSUE TITLE
Keyboard hides Textboxes

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#520]
Depending on display size and placement of the textbox control it occurs that the textbox is hidden by the keyboard or the appbar.

Maybe this issue has the solution: http://stackoverflow.com/questions/27297205/soft-keyboard-overlaps-textboxes-and-makes-them-unreachable

**Comment by NPadrutt** [comment]
@lorenzofar do you have an idea how we can solve this?
the scollviewer itself didn't fully fix it. The problem is that the app bar is also moving and therefore is overlapping.

**Comment by lorenzofar** [comment]
@NPadrutt I'll try and then i'll let you know

**Comment by NPadrutt** [comment]
@lorenzofar it seems that is a bug in the plattform..
https://social.msdn.microsoft.com/Forums/vstudio/en-US/a480fbc5-938c-4805-b449-220d4500b3a0/uwpbottom-appbar-sticks-to-onscreen-keyboard-in-windows-10-app?forum=wpdevelop&prof=required

**Comment by NPadrutt** [comment]
This is solved with the monkey patch from the forum thread above.
