### ISSUE TITLE
Scroll viewer in account creation

### ISSUE THREAD

**Issue by lorenzofar** [Apply-Solutions/MoneyManager#525]
[WINDOWS 10 mobile] You should add a scrollviewer in the account creation page, to make the page scrollable when keyboard is shown

**Comment by NPadrutt** [comment]
Good point. Do you wanna have a look at that? :)

**Comment by NPadrutt** [comment]
I thought about it. while it makes perfectly sense to add a scrollviewer to the account creation page, I'm not sure this will fix the issue with the keyboard who overlaps some controls.. See  issue #520

**Comment by lorenzofar** [comment]
I'll have a look at that. I think this could also solve issue #520

**Comment by NPadrutt** [comment]
Alright, nice :)

**Comment by NPadrutt** [comment]
I had a quick look. If you have text suggestions activated the app bar still hides the textbox. For example when you select the Note Textbox.

**Comment by NPadrutt** [comment]
I merged your commit to the v1.1 branch that it is in the update going out in the next couple of hours. I guess the thing with the overlapping keyboard can be threaded generally in #520
