### ISSUE TITLE
Crashes on the About screen

### ISSUE THREAD

**Issue by Ventajou** [Apply-Solutions/MoneyManager#526]
I can reproduce this one every time:

- Open the app
- Go to Settings, then Security
- Got to About... boom!

**Comment by NPadrutt** [comment]
oh, good one =)
Shall I fix or do you wanna try by you own? =)

**Comment by NPadrutt** [comment]
I had a idea what id could be. But it's a bit strange since the error doesn't occur when you are debugging... I try it with the beta version.

**Comment by NPadrutt** [comment]
this should be fixed =)
