### ISSUE TITLE
Enable Enter key in category dialog to save entry

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#541]

**Comment by lorenzofar** [comment]
You can add the keydown handler in the textbox's XAML declaration, then in the code you get the parameter (e.Key) and if it's equal to the enter key you do something (like saving the entry).

**Comment by NPadrutt** [comment]
Yeah. There are plenty of places where that would be useful (e.g. #541). Wanna have a look at that? :)
