### ISSUE TITLE
Enable enter key on select category view

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#542]

**Comment by NPadrutt** [comment]
I tried somehing here but it's not really done yet. When the list is selected the event isn't fired. Maybe someone else does have an idea here.

**Comment by lorenzofar** [comment]
I don't know if i understood well, do you want to select an item in the list and then do something when the enter key is pressed?

**Comment by lorenzofar** [comment]
If so, you should attach the keyDown handler to the ListView and then when you handle the event you first check if the pressed key was enter and then if an item is selected

**Comment by NPadrutt** [comment]
The idea is, that you can select a category and close the selection with hit enter instead of click the done button.
I tried to add a keyDown handler to the listview, but it somehwo didn't work,.. =(

**Comment by lorenzofar** [comment]
I think you should attach the keydown handler to the stack panel (or the element containing all the other elements), because when you select an item the textbox loses focus and cannot fire the keydown event

**Comment by NPadrutt** [comment]
I tried to add it to the list itself or to the grid. Im not sure, but I guess the problem is, that a stackpanel won't ever have focus, since it passes it straight down to the next control. But I added an handler on level user control. But it doesn't work for the lust.. Not sure if the list swallows the handler..
