### ISSUE TITLE
Support for jumplists on the desktop

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#573]
This should be available in the sdk 1586.

**Comment by lorenzofar** [comment]
Hello, adding jump lists is simple and I'll add the code asap.
In the meantime you should create icons for the jump lists.

**Comment by NPadrutt** [comment]
Sounds great :+1:  :)

**Comment by lorenzofar** [comment]
using Windows.UI.StartScreen;

protected override async void OnLaunched(LaunchActivatedEventArgs e)
{
    if (Windows.Foundation.Metadata.ApiInformation.IsEventPresent("Windows.UI.StartScreen", "JumpList")) //Checks if the API is supported (build > 10586)
    {
        var jump_list = await JumpList.LoadCurrentAsync();
        jump_list.Items.Clear();
        jump_list.SystemGroupKind = JumpListSystemGroupKind.None; //The group for static links
        #region Create and Add the jump list (repeat for every jump list you want to add)
        JumpListItem jump_list = JumpListItem.CreateWithArguments(/*Insert the argument (string)*/"", /*Insert the text of the jump list*/"");
        jump_list.Logo = new Uri(/*Insert the path of the .png file*/ "ms-appx:///Assets/jump_list_icon.png");
        jump_list.Items.Add(jump_list);
        #endregion
        await jump_list.SaveAsync();
    }
.}

**Comment by lorenzofar** [comment]
You have to  put this in the app.xaml.cs file

**Comment by lorenzofar** [comment]
I made a typo, this is the correct code:

using Windows.UI.StartScreen;

protected override async void OnLaunched(LaunchActivatedEventArgs e)
{
 if (Windows.Foundation.Metadata.ApiInformation.IsEventPresent("Windows.UI.StartScreen", "JumpList")) //Checks if the API is supported (build > 10586)
 {
 var jump_list = await JumpList.LoadCurrentAsync();
 jump_list.Items.Clear();
 jump_list.SystemGroupKind = JumpListSystemGroupKind.None; //The group for static links
 #region Create and Add the jump list (repeat for every jump list you want to add)
 JumpListItem list_item = JumpListItem.CreateWithArguments(/Insert the argument (string)/"", /Insert the text of the jump list/"");
 list_item.Logo = new Uri(/Insert the path of the .png file/ "ms-appx:///Assets/jump_list_icon.png");
 jump_list.Items.Add(list_item);
 #endregion
 await jump_list.SaveAsync();
 }
 }

**Comment by NPadrutt** [comment]
Thansk. Working on a concrete implementation, but wad interrupted. I'll let you know when I'm finished.

**Comment by NPadrutt** [comment]
@lorenzofar  I tried this, but can't resolve the Jumplist properly. Do I have to to import something specially? I have the latest VS 2015 installed.
You can see what I tried in the jumplist branch in my repo.
https://github.com/NPadrutt/MoneyManager/tree/jumplist

**Comment by lorenzofar** [comment]
I think you should import the Windows.UI.StartScreen namespace.
I made a mistake in the apiinformation check, i'll send you the correct method (you don't have to check if an event is supported, but the JumpList object)

**Comment by NPadrutt** [comment]
I imported it. and Resharper doesn't show something. I assume there should be something I have to reference or so. You can give it a try if you want.

**Comment by lorenzofar** [comment]
I fixed this issue in the latest pull request.

**Comment by NPadrutt** [comment]
Thanks for your help =)
