### ISSUE TITLE
Split View should close when tapping a button

### ISSUE THREAD

**Issue by lorenzofar** [Apply-Solutions/MoneyManager#588]
The split view (hamburger menu) should close when navigating to a page, like in system apps.

**Comment by NPadrutt** [comment]
Yeah, I agree. Do you know a place where that's not the case?

**Comment by NPadrutt** [comment]
ah and do you mean on the phone or the desktop?

**Comment by lorenzofar** [comment]
On the desktop when the window is not full screen.

**Comment by NPadrutt** [comment]
aah, I see. this is when you have the window small so that the split view isn't permanently shown, right?  (I hope you mean what I try to describe ^^ )

**Comment by NPadrutt** [comment]
I guess this is fixed with #616.
