### ISSUE TITLE
App crashes when entering password

### ISSUE THREAD

**Issue by lorenzofar** [Apply-Solutions/MoneyManager#603]
The app crashes when i click the login button or i press the enter key.

**Comment by NPadrutt** [comment]
uh, ugly. Thanks for reporting.

**Comment by lorenzofar** [comment]
I tried to debug, i'll send you the error message.

**Comment by NPadrutt** [comment]
guess I found it. I made a change for the IoC. Since then, only the Interface IPasswordStorage was registered and not PasswordStorage itself. So it failed to resolve. I make a PR who fix that.

**Comment by NPadrutt** [comment]
should work again. can you try it again?

**Comment by NPadrutt** [comment]
@lorenzofar there is an update for the beta. and I wil backport this fix to 1.3 I guess.

**Comment by NPadrutt** [comment]
I'll close this. please reopen if the error is still present.

**Comment by lorenzofar** [comment]
Sorry for the late, it now works.

**Comment by NPadrutt** [comment]
great, thanks for the info! =)
