### ISSUE TITLE
Change display mode of the menu to CompactOverlay

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#616]
Maybe this provides a better usability.

**Comment by NPadrutt** [comment]
On small devices this consumes to much space I guess. But it might make sense for bigger devices.

**Comment by MichaelAi** [comment]
Definitely, keep it hidden for small screens.

**Comment by NPadrutt** [comment]
I tried something. we will see how it works

**Comment by NPadrutt** [comment]
Opinions?

**Comment by MichaelAi** [comment]
Better this way, although i still think that compact overlay on larger windows looks nicer, but hey that's just my opinion and you are the owner of the project :)

**Comment by NPadrutt** [comment]
you mean CompactOverlay instead of Compact Inline?

I'm not sure yet. The Compact  Overlay looks more symetrical

**Comment by NPadrutt** [comment]
I leave it that way for the moment. I hope to get more feedback on this with the next update.
