### ISSUE TITLE
NullReferenceException when adding a transaction for the first time

### ISSUE THREAD

**Issue by MichaelAi** [Apply-Solutions/MoneyManager#633]
Every time i try to add a transaction, when there are no others, i get a nullreferenceexception in the ModifyTransasctionViewModel.

Edit: It doesn't actually crash it, sorry. But still inelegant.,

**Comment by MichaelAi** [comment]
Can be fixed by changing the viewmodel to call PrepareDefault(typestring) when IsEdit is false, insteading or returning (line ~58). Not sure about the consequences of this, but think about it.

**Comment by NPadrutt** [comment]
Thanks! I'll have a  look.
