### ISSUE TITLE
Commandbar covers up splitview pane in statistics page

### ISSUE THREAD

**Issue by MichaelAi** [Apply-Solutions/MoneyManager#634]
I'm pretty sure i fixed that but the commandbar covers the splitview pane in statistics page again.

**Comment by NPadrutt** [comment]
Is it possible that a merge reverted your change ?

**Comment by NPadrutt** [comment]
aah, it is fixed. just not everywhere :dancer:

**Comment by NPadrutt** [comment]
I guess you have to do the same in the statistic view as well
