### ISSUE TITLE
cach loaded transaction data

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#645]

**Comment by MichaelAi** [comment]
Can give you more details on what exactly do you mean?

**Comment by NPadrutt** [comment]
for example if you select an account it will load the related transactions for it. if you go back and select the same again it will reload all data. This always needs a 1-3 seconds and is more or less wasted time.

also if you are in the transaction view and add a transaction or cancel adding a transaction it will navigate back and again load all data.

this is due to the old logic where all transactions where loaded on startup. maybe we should just load all of them the first time they are used and then cache them.

**Comment by NPadrutt** [comment]
Mh, I make a try with that. Then we see if it works or not. =)

**Comment by NPadrutt** [comment]
Maybe we should go to load all transactions on start but do it async..

**Comment by NPadrutt** [comment]
I did some research. Turns out there is plenty of potential in startup speed without so much change. I still making some tests. But it looks promising.

**Comment by NPadrutt** [comment]
I close this for the moment. We will see how good it behaves after we finished the next update.
